//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.RankPro.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar_reqdept
    {
        public int Id { get; set; }
        public string sid { get; set; }
        public string reqid { get; set; }
        public string ffrom { get; set; }
        public int ddays { get; set; }
        public string tto { get; set; }
        public int deptcode { get; set; }
        public int deptsub { get; set; }
        public int dclass { get; set; }
        public int classsub { get; set; }
        public string daterequested { get; set; }
        public string status { get; set; }
        public string exptn { get; set; }
    }
}
