//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.RankPro.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar_sms
    {
        public int Id { get; set; }
        public string sid { get; set; }
        public string region { get; set; }
        public string icurrent { get; set; }
        public string timesent { get; set; }
        public string status { get; set; }
    }
}
