//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.RankPro.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dnbmssqlEntities : DbContext
    {
        public dnbmssqlEntities()
            : base("name=dnbmssqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<C_Role> C_Role { get; set; }
        public virtual DbSet<C_User> C_User { get; set; }
        public virtual DbSet<C_UserClaim> C_UserClaim { get; set; }
        public virtual DbSet<C_UserLogin> C_UserLogin { get; set; }
        public virtual DbSet<ar_po> ar_po { get; set; }
        public virtual DbSet<ar_reqbrand> ar_reqbrand { get; set; }
        public virtual DbSet<ar_reqdept> ar_reqdept { get; set; }
        public virtual DbSet<ar_reqlist> ar_reqlist { get; set; }
        public virtual DbSet<ar_reqsku> ar_reqsku { get; set; }
        public virtual DbSet<ar_rtv> ar_rtv { get; set; }
        public virtual DbSet<ar_sms> ar_sms { get; set; }
        public virtual DbSet<po> poes { get; set; }
        public virtual DbSet<reqbrand> reqbrands { get; set; }
        public virtual DbSet<reqdept> reqdepts { get; set; }
        public virtual DbSet<reqlist> reqlists { get; set; }
        public virtual DbSet<reqpayment> reqpayments { get; set; }
        public virtual DbSet<reqpaymentlist> reqpaymentlists { get; set; }
        public virtual DbSet<reqpaystatement> reqpaystatements { get; set; }
        public virtual DbSet<reqsku> reqskus { get; set; }
        public virtual DbSet<rtv> rtvs { get; set; }
        public virtual DbSet<sm> sms { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<supplieractivtion> supplieractivtions { get; set; }
        public virtual DbSet<supplierlog> supplierlogs { get; set; }
        public virtual DbSet<supplierregion> supplierregions { get; set; }
        public virtual DbSet<syssupcomp> syssupcomps { get; set; }
        public virtual DbSet<syssupcomprply> syssupcomprplies { get; set; }
        public virtual DbSet<syssuplog> syssuplogs { get; set; }
        public virtual DbSet<userapp> userapps { get; set; }
        public virtual DbSet<ViewRankingBrandRequest> ViewRankingBrandRequests { get; set; }
        public virtual DbSet<ViewRankingDeptRequest> ViewRankingDeptRequests { get; set; }
        public virtual DbSet<ViewRankingSKURequest> ViewRankingSKURequests { get; set; }
    
        public virtual int spbrandreqarchive(string datexpiration)
        {
            var datexpirationParameter = datexpiration != null ?
                new ObjectParameter("Datexpiration", datexpiration) :
                new ObjectParameter("Datexpiration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spbrandreqarchive", datexpirationParameter);
        }
    
        public virtual int spdeptreqarchive(string datexpiration)
        {
            var datexpirationParameter = datexpiration != null ?
                new ObjectParameter("Datexpiration", datexpiration) :
                new ObjectParameter("Datexpiration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spdeptreqarchive", datexpirationParameter);
        }
    
        public virtual int sppoarchive(string datexpiration)
        {
            var datexpirationParameter = datexpiration != null ?
                new ObjectParameter("Datexpiration", datexpiration) :
                new ObjectParameter("Datexpiration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sppoarchive", datexpirationParameter);
        }
    
        public virtual int sprtvarchive(Nullable<System.DateTime> datexpiration)
        {
            var datexpirationParameter = datexpiration.HasValue ?
                new ObjectParameter("Datexpiration", datexpiration) :
                new ObjectParameter("Datexpiration", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sprtvarchive", datexpirationParameter);
        }
    
        public virtual int spskureqarchive(string datexpiration)
        {
            var datexpirationParameter = datexpiration != null ?
                new ObjectParameter("Datexpiration", datexpiration) :
                new ObjectParameter("Datexpiration", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spskureqarchive", datexpirationParameter);
        }
    
        public virtual int spsmsarchive()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spsmsarchive");
        }
    }
}
