//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.RankPro.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqpaymentlist
    {
        public int Id { get; set; }
        public string reqid { get; set; }
        public string invoicenum { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
    }
}
