//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.RankPro.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssupcomp
    {
        public int Id { get; set; }
        public string userid { get; set; }
        public string issueid { get; set; }
        public string issuename { get; set; }
        public string issuetype { get; set; }
        public string comment { get; set; }
        public string issuedate { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
    }
}
