//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.Mobile.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class po
    {
        public int Id { get; set; }
        public string sid { get; set; }
        public string pono { get; set; }
        public string region { get; set; }
        public string location { get; set; }
        public string division { get; set; }
        public string link { get; set; }
        public string filestatus { get; set; }
        public string released { get; set; }
        public string expiration { get; set; }
        public string isexpired { get; set; }
    }
}
