//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.Mobile.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class reqpaystatement
    {
        public int Id { get; set; }
        public string sid { get; set; }
        public string reqid { get; set; }
        public string statementlist { get; set; }
        public string dateuploaded { get; set; }
        public string status { get; set; }
    }
}
