//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Win.Mobile.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRankingSKURequest
    {
        public string sid { get; set; }
        public string reqid { get; set; }
        public string ffrom { get; set; }
        public int ddays { get; set; }
        public string tto { get; set; }
        public string sku1 { get; set; }
        public string sku2 { get; set; }
        public string sku3 { get; set; }
        public string sku4 { get; set; }
        public string sku5 { get; set; }
        public string dreq { get; set; }
        public string rtype { get; set; }
        public string exprtn { get; set; }
        public string sts { get; set; }
        public string lnk { get; set; }
        public string lnka { get; set; }
        public string exprd { get; set; }
    }
}
