//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Web.Admin.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierregion
    {
        public int Id { get; set; }
        public string sid { get; set; }
        public string region { get; set; }
        public string password { get; set; }
        public string mobile { get; set; }
        public string sms { get; set; }
        public string status { get; set; }
    }
}
